### PR TITLE
Add Japanese version of FAQs

### PR DESCRIPTION
**Pull request by shu-mutou**
Invited colleagues listed below and had them experience contributing.

@s-uramoto, @y-ksmt-01, @taka-takeuchi, @sugiyama-m-v, @s-kazuyoshi, @ogura-kei, @natsuki-takase, @liumiiin, @kinpara-s, @k-hiraiwa, @shogo-katada, @i-kenta and @ziyi-xie.

### CODE REVIEW

**Comment by shu-mutou** [comment]
Could you let me know how to redirect URL (`/ja/faqs/`) to `/content/ja/faq/` directory?

**Comment by shu-mutou** [comment]
@anajsana This PR is ready for reviewing, thanks!

**Comment by shu-mutou** [comment]
@anajsana I am sorry to intrude on your precious time, but could you please check this PR?

**Review by anajsana — APPROVED** [review]

**Comment by anajsana** [comment]
Thanks for your contributions team! LGTM 😊

**Pull request merged**
