### PR TITLE
Replacing RIT logo

### PR DESCRIPTION
**Pull request by amye**

### CODE REVIEW

**Comment by decause** [comment]
Full logo/branding page for RIT can be found here: https://www.rit.edu/marketing/brandportal/toolkits/logos

Perhaps this one is the preferred one? https://www.rit.edu/marketing/brandportal/images/1505/toolkits/logo/RIT_RGB_hor.png
Maybe @nolski could confirm with @itprofjacobs which one y'all'd prefer?

**Comment by amye** [comment]
This is the one that came from @itprofjacobs

**Comment by anajsana** [comment]
Hi there! What is missing from this PR to be merged? Is there anything I can help with @amye @decause ? :blush:

**Comment by caniszczyk** [comment]
This was done via the landscape

**Pull request closed without merging**
