### PR TITLE
Employee Open Source Engagement Guide

### PR DESCRIPTION
**Pull request by cornelius**
This pull request supersedes #384. It incorporates the comments from the last call of the group working on the guide. It's still a draft. Further comments and refinements are welcome.

### CODE REVIEW

**Comment by anajsana** [comment]
hey @cornelius are they any updates from the Employee Open Source Engagement Working Group? Should we go ahead and merge this version?

**Comment by cornelius** [comment]
There were no specific updates anymore. I will use an event next week to gather a bit more feedback and then create a version for final review.

**Comment by cornelius** [comment]
One feedback I got: The wording of the principle "Enforce respectful behavior" is a bit out of line with the other principles as the enforcement part is something the contributor might not be able to do as this is more an activity of the community or specific people in the community who take care of that. It still is important that people are held accountable to adhere to the code of conduct by all members of the community. Maybe there is a better term, which is a bit less intimidating.

**Comment by anajsana** [comment]
@cornelius and all: I'm reviewing all the open PRs in this repo that were opened more than 3 months ago to determine if they can be closed. Given the guide's long-term inactivity in terms of new additions or contributions, and since the content is no longer being updated, I will go ahead and merge this PR. Should there be any additional changes in the coming weeks, please open a new PR to update the current version

**Comment by anajsana** [comment]
> @cornelius and all: I'm reviewing all the open PRs in this repo that were opened more than 3 months ago to determine if they can be closed. Given the guide's long-term inactivity in terms of new additions or contributions, and since the content is no longer being updated, I will go ahead and merge this PR. Should there be any additional changes in the coming weeks, please open a new PR to update the current version

PS: The same process should be applied if this working group opts to develop a new version of the guide in the future. In light of this, I suggest transitioning this project into a maintenance phase.

**Review by anajsana — APPROVED** [review]

**Comment by anajsana** [comment]
> One feedback I got: The wording of the principle "Enforce respectful behavior" is a bit out of line with the other principles as the enforcement part is something the contributor might not be able to do as this is more an activity of the community or specific people in the community who take care of that. It still is important that people are held accountable to adhere to the code of conduct by all members of the community. Maybe there is a better term, which is a bit less intimidating.

as an alternative word, we can use "Promote and uphold respectful behavior"

**Pull request merged**
